### ISSUE TITLE
ServerUtils Velocity plugin issue

### ISSUE THREAD

**Issue by Mahmud180** [GemstoneGG/Velocity-CTD#227]
The error on startup : 
 
[03:59:57 ERROR]: Couldn't pass ProxyInitializeEvent to serverutils 3.5.4
java.lang.UnsupportedOperationException: StampedConfig does not support valueMap() yet.
        at com.electronwill.nightconfig.core.concurrent.StampedConfig.valueMap(StampedConfig.java:472) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)]
        at com.electronwill.nightconfig.core.utils.UnmodifiableConfigWrapper.valueMap(UnmodifiableConfigWrapper.java:29) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)]
        at net.frankheijden.serverutils.velocity.entities.VelocityTomlConfig.getKeys(VelocityTomlConfig.java:85) ~[?:?]
        at net.frankheijden.serverutils.common.config.ServerUtilsConfig.removeOldKeys(ServerUtilsConfig.java:145) ~[?:?]
        at net.frankheijden.serverutils.common.config.ServerUtilsConfig.removeOldKeys(ServerUtilsConfig.java:137) ~[?:?]
        at net.frankheijden.serverutils.common.config.ServerUtilsConfig.init(ServerUtilsConfig.java:164) ~[?:?]
        at net.frankheijden.serverutils.common.config.ServerUtilsConfig.init(ServerUtilsConfig.java:190) ~[?:?]
        at net.frankheijden.serverutils.common.config.ServerUtilsResource.<init>(ServerUtilsResource.java:25) ~[?:?]
        at net.frankheijden.serverutils.common.config.CommandsResource.<init>(CommandsResource.java:16) ~[?:?]
        at net.frankheijden.serverutils.common.entities.ServerUtilsPlugin.reload(ServerUtilsPlugin.java:181) ~[?:?]
        at net.frankheijden.serverutils.common.entities.ServerUtilsPlugin.enable(ServerUtilsPlugin.java:154) ~[?:?]
        at net.frankheijden.serverutils.velocity.ServerUtils.onEnable(ServerUtils.java:86) ~[?:?]
        at net.frankheijden.serverutils.velocity.Lmbda$50.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:594) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:475) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        
        
        
  Version : Velocity 3.3.0-SNAPSHOT (git-9575ab44)
  
  DUMP: [velocity-dump-2024-06-01-04-01-53.json](https://github.com/user-attachments/files/15520332/velocity-dump-2024-06-01-04-01-53.json)

**Comment by R00tB33rMan** [comment]
> The error on startup :
> 
> [03:59:57 ERROR]: Couldn't pass ProxyInitializeEvent to serverutils 3.5.4 java.lang.UnsupportedOperationException: StampedConfig does not support valueMap() yet. at com.electronwill.nightconfig.core.concurrent.StampedConfig.valueMap(StampedConfig.java:472) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)] at com.electronwill.nightconfig.core.utils.UnmodifiableConfigWrapper.valueMap(UnmodifiableConfigWrapper.java:29) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)] at net.frankheijden.serverutils.velocity.entities.VelocityTomlConfig.getKeys(VelocityTomlConfig.java:85) ~[?:?] at net.frankheijden.serverutils.common.config.ServerUtilsConfig.removeOldKeys(ServerUtilsConfig.java:145) ~[?:?] at net.frankheijden.serverutils.common.config.ServerUtilsConfig.removeOldKeys(ServerUtilsConfig.java:137) ~[?:?] at net.frankheijden.serverutils.common.config.ServerUtilsConfig.init(ServerUtilsConfig.java:164) ~[?:?] at net.frankheijden.serverutils.common.config.ServerUtilsConfig.init(ServerUtilsConfig.java:190) ~[?:?] at net.frankheijden.serverutils.common.config.ServerUtilsResource.(ServerUtilsResource.java:25) ~[?:?] at net.frankheijden.serverutils.common.config.CommandsResource.(CommandsResource.java:16) ~[?:?] at net.frankheijden.serverutils.common.entities.ServerUtilsPlugin.reload(ServerUtilsPlugin.java:181) ~[?:?] at net.frankheijden.serverutils.common.entities.ServerUtilsPlugin.enable(ServerUtilsPlugin.java:154) ~[?:?] at net.frankheijden.serverutils.velocity.ServerUtils.onEnable(ServerUtils.java:86) ~[?:?] at net.frankheijden.serverutils.velocity.Lmbda$50.execute(Unknown Source) ~[?:?] at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)] at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:594) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)] at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:475) ~[server.jar:3.3.0-SNAPSHOT (git-9575ab44)] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> 
> Version : Velocity 3.3.0-SNAPSHOT (git-9575ab44)
> 
> DUMP: [velocity-dump-2024-06-01-04-01-53.json](https://github.com/user-attachments/files/15520332/velocity-dump-2024-06-01-04-01-53.json)

The author of ServerUtils needs to implement compatibility for non-labeled build handling. This means that ServerUtils requires a build number to be labeled for compatibility. I'd encourage contacting the author in favor of resolving this issue. There's sadly nothing we can do. If this isn't the case and I'm misinterpreting this error, the author likely needs to upgrade their NightConfig version for later support.

**Comment by R00tB33rMan** [comment]
As far as I'm concerned, this resource isn't maintained. Additionally, Velocity, at some point, will likely upgrade to the latest iteration of NightConfig, which will break compatibility for this resource anyway. I'd encourage looking into alternatives or having the author update this if it is plausible.
