### ISSUE TITLE
This error prevented my server from shutting down.

### ISSUE THREAD

**Issue by Noogear** [GemstoneGG/Velocity-CTD#388]
### Expected Behavior

Shut down the server

### Actual Behavior

This error prevented my server from shutting down.
```
[14:33:57 INFO]: Closing endpoint /0.0.0.0:25565
[14:33:57 ERROR]: Exception in thread "Thread-2" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[14:33:57 ERROR]:       at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[14:33:57 ERROR]:       at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[14:33:57 ERROR]:       at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[14:33:57 ERROR]:       at java.base/java.util.Objects.checkIndex(Objects.java:365)
[14:33:57 ERROR]:       at java.base/java.util.ArrayList.get(ArrayList.java:428)
[14:33:57 ERROR]:       at com.velocitypowered.proxy.VelocityServer.getProxyAddressToUse(VelocityServer.java:961)
[14:33:57 ERROR]:       at com.velocitypowered.proxy.VelocityServer.lambda$shutdown$12(VelocityServer.java:824)
[14:33:57 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Steps to Reproduce

Shut down the server

### Plugin List

velocity, commandwhitelist, fastmotd, forcepack, packetevents, signedvelocity, skinsrestorer

### Velocity Version

Velocity 3.4.0-SNAPSHOT (git-c080c936)

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> Shut down the server
> 
> ### Actual Behavior
> This error prevented my server from shutting down.
> 
> ```
> [14:33:57 INFO]: Closing endpoint /0.0.0.0:25565
> [14:33:57 ERROR]: Exception in thread "Thread-2" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
> [14:33:57 ERROR]:       at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
> [14:33:57 ERROR]:       at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
> [14:33:57 ERROR]:       at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
> [14:33:57 ERROR]:       at java.base/java.util.Objects.checkIndex(Objects.java:365)
> [14:33:57 ERROR]:       at java.base/java.util.ArrayList.get(ArrayList.java:428)
> [14:33:57 ERROR]:       at com.velocitypowered.proxy.VelocityServer.getProxyAddressToUse(VelocityServer.java:961)
> [14:33:57 ERROR]:       at com.velocitypowered.proxy.VelocityServer.lambda$shutdown$12(VelocityServer.java:824)
> [14:33:57 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1570)
> ```
> 
> ### Steps to Reproduce
> Shut down the server
> 
> ### Plugin List
> velocity, commandwhitelist, fastmotd, forcepack, packetevents, signedvelocity, skinsrestorer
> 
> ### Velocity Version
> Velocity 3.4.0-SNAPSHOT (git-c080c936)
> 
> ### Additional Information
> _No response_

Able to provide us a snippet of your configuration?

**Comment by Noogear** [comment]
[velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip)
Yeah. It's here.

**Comment by R00tB33rMan** [comment]
> [velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip) Yeah. It's here.

Can you regenerate your configuration? I notice you're missing a lot of important categories/sections. If you wish not to use our queue system, simply disable the value at the top of the subsection.

**Comment by R00tB33rMan** [comment]
> [velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip) Yeah. It's here.

Issue is resolved once we merge our development branch. We're working out some other bugs and issues prior!

**Comment by Noogear** [comment]
> > [velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip) Yeah. It's here.
> 
> Issue is resolved once we merge our development branch. We're working out some other bugs and issues prior!

Is there a better solution at present? Every time I restart the server, I have to restart the entire system.

**Comment by R00tB33rMan** [comment]
> > > [velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip) Yeah. It's here.
> > 
> > 
> > Issue is resolved once we merge our development branch. We're working out some other bugs and issues prior!
> 
> Is there a better solution at present? Every time I restart the server, I have to restart the entire system.

Hey! We're merging our development branch into our main branch soon. When it relates to better solution, do you mean one better than the one we already applied our development branch?

**Comment by Noogear** [comment]
> > > > [velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip) Yeah. It's here.
> > > 
> > > 
> > > Issue is resolved once we merge our development branch. We're working out some other bugs and issues prior!
> > 
> > 
> > Is there a better solution at present? Every time I restart the server, I have to restart the entire system.
> 
> Hey! We're merging our development branch into our main branch soon. When it relates to better solution, do you mean one better than the one we already applied our development branch?

Sorry. What I meant was that I'm really looking forward to this development version and hope it can be released soon.

**Comment by R00tB33rMan** [comment]
We have hopes to push this soon. We really want to resolve our queue system breakages prior to pushing this fixed branch to production! We apologize for the wait. The holidays got in the way of us working persistently on this project.

**Comment by R00tB33rMan** [comment]
> > > > > [velocity.zip](https://github.com/user-attachments/files/18200020/velocity.zip) Yeah. It's here.
> > > > 
> > > > 
> > > > Issue is resolved once we merge our development branch. We're working out some other bugs and issues prior!
> > > 
> > > 
> > > Is there a better solution at present? Every time I restart the server, I have to restart the entire system.
> > 
> > 
> > Hey! We're merging our development branch into our main branch soon. When it relates to better solution, do you mean one better than the one we already applied our development branch?
> 
> Sorry. What I meant was that I'm really looking forward to this development version and hope it can be released soon.

Resolved. Closing!
